{% set name = "sphinxcontrib-spelling" %}
{% set version = "5.0.0" %}
{% set sha256 = "a1070b74d8509f4d02c74cb1c187bbde95b0178338aff88fedea3c672b099f4e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pbr
  run:
    - python

test:
  imports:
    - sphinxcontrib

about:
  home: https://bitbucket.org/dhellmann/sphinxcontrib-spelling
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: This package contains sphinxcontrb.spelling, a spelling checker for Sphinx-based documentation.
  description: |
    This package contains sphinxcontrb.spelling, a spelling checker 
    for Sphinx-based documentation. It uses PyEnchant to produce 
    a report showing misspelled words.
  doc_url: https://bitbucket.org/dhellmann/sphinxcontrib-spelling
  dev_url: https://bitbucket.org/dhellmann/sphinxcontrib-spelling

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
