{% set name = "sphinxcontrib-spelling" %}
{% set version = "8.0.1" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f0447b6413c78b613b916c7891e36be85a105d1919c99784c53dfea2d8f8040f
  patches:
    - 0001-gracefully-handle-if-git-is-not-installed.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - pyenchant >=3.1.1
    - sphinx >=3.0.0

test:
  imports:
    - sphinxcontrib.spelling
  commands:
    - pip check
    # Workaround for bug in hunspell that breaks pyenchant
    # See: https://github.com/conda-forge/hunspell-feedstock/issues/12
    - ln -s $CONDA_PREFIX/share/hunspell_dictionaries $CONDA_PREFIX/share/enchant/hunspell
    - python -m pytest -vv
  source_files:
    - tests/
    - tox.ini
  requires:
    - python {{ python_min }}
    - pip
    - pytest

about:
  home: https://sphinxcontrib-spelling.readthedocs.io/en/latest/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'This package contains sphinxcontrb.spelling, a spelling checker for Sphinx-based documentation.'
  description: |
    This package contains sphinxcontrb.spelling, a spelling checker
    for Sphinx-based documentation. It uses PyEnchant to produce
    a report showing misspelled words.
  dev_url: https://github.com/sphinx-contrib/spelling

extra:
  recipe-maintainers:
    - blmaier
    - cshaley
    - sannykr
